import { Button, VerticalBox, HorizontalBox, TextEdit, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Equinox";

    out property <string> blog_title;
    out property <string> blog_content;

    callback generate_page();
    VerticalBox {
        HorizontalBox {
            Text {
                font-size: 18px;
                font-weight: 600;
                text: "Title";
            }
            LineEdit {
                font-size: 18px;
                width: 700px;
                height: 50px;
                edited(string) => {
                    blog_title = string
                };
            }
        }
        HorizontalBox {
            Text {
                font-size: 18px;
                font-weight: 600;
                text: "Content";
            }
            TextEdit {
                font-size: 14px;
                width: 700px;
                height: 500px;
                edited(text) => {
                    blog_content = text;
                }
            }
        }
        Button {
            text: "Generate";
            clicked => {
                root.generate_page();
            }
        }
    }
    
}

import { StandardButton, Button } from "std-widgets.slint";
export component ErrorWindow inherits Dialog {
    in property <string> error_window_content;

    Text {
      text: error_window_content;
    }
    StandardButton { 
        kind: ok;
    }
}